<?php

$args = array( 'post_type' => 'tiles', 'posts_per_page' => -1 );
$loop = new WP_Query( $args );
$arr = array();
while ( $loop->have_posts() ) : $loop->the_post();
    $item = array();
    $item['tile_type'] = get_post_meta( get_the_ID(), '_tmx_tile_type', true)[0];
    $item['name'] = get_the_title();
    $item['cat_a_title'] = get_the_title();
    $item['cat_b_title'] = "Type-".get_post_meta( get_the_ID(), '_tmx_tile_type', true)[0];
    $item['grout_id'] = 1;
    $item['grout_color'] = get_post_meta( get_the_ID(), '_tmx_tile_color', true);;
    $item['with_no_grouth'] = false;
    $item['price'] = get_post_meta( get_the_ID(), '_tmx_tile_price', true);
    $item['link'] = '-';
    $item['size'] = array(600,600);
    $item['id'] = get_the_ID();
    $item['image'] = wp_get_attachment_url( get_post_thumbnail_id(get_the_ID()) );
    $item['similar_images'] = array();
    $item['cat_b_id'] = 12;
    $item['filters'] = null;
    $arr[get_the_ID()] = array();
    $arr[get_the_ID()] = $item;
endwhile;
wp_reset_query();

print_r(json_encode($arr));

/*
{
            "4": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 4,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_28.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "39": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 39,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_84.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "40": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 40,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_85.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "41": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 41,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_86.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "42": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 42,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_87.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "43": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 43,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_88.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "44": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 44,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_89.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "45": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 45,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_90.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "46": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 46,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_91.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "47": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 47,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_92.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "48": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 48,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_93.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "49": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 49,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_94.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "50": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 50,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_95.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "51": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 51,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_96.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "52": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 52,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_97.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "53": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 53,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_98.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "54": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 54,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_99.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "55": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 55,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_100.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "56": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 56,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_101.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "57": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 57,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_102.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "58": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 58,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_103.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "59": {
                "tile_type": 1,
                "name": "Title",
                "cat_a_title": "Wallpaper",
                "cat_b_title": "Type-1",
                "grout_id": "3",
                "grout_color": "#ffffff",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "300"],
                "id": 59,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_110.jpg",
                "similar_images": [],
                "cat_b_id": 15,
                "filters": null
            },
            "60": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Ceramic Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 60,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_19.jpg",
                "similar_images": [],
                "cat_b_id": 10,
                "filters": null
            },
            "61": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Ceramic Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 61,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_20.jpg",
                "similar_images": [],
                "cat_b_id": 10,
                "filters": null
            },
            "62": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Ceramic Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "3",
                "grout_color": "#ffffff",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 62,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_21.jpg",
                "similar_images": [],
                "cat_b_id": 10,
                "filters": null
            },
            "64": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Ceramic Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 64,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_47.jpg",
                "similar_images": [],
                "cat_b_id": 10,
                "filters": null
            },
            "65": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Ceramic Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 65,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_48.jpg",
                "similar_images": [],
                "cat_b_id": 10,
                "filters": null
            },
            "66": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Ceramic Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 66,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_49.jpg",
                "similar_images": [],
                "cat_b_id": 10,
                "filters": null
            },
            "67": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Ceramic Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 67,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_50.jpg",
                "similar_images": [],
                "cat_b_id": 10,
                "filters": null
            },
            "68": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Ceramic Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 68,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_51.jpg",
                "similar_images": [],
                "cat_b_id": 10,
                "filters": null
            },
            "69": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Ceramic Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 69,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_52.jpg",
                "similar_images": [],
                "cat_b_id": 10,
                "filters": null
            },
            "70": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Ceramic Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 70,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_53.jpg",
                "similar_images": [],
                "cat_b_id": 10,
                "filters": null
            },
            "71": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Ceramic Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 71,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_54.jpg",
                "similar_images": [],
                "cat_b_id": 10,
                "filters": null
            },
            "72": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Ceramic Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 72,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_55.jpg",
                "similar_images": [],
                "cat_b_id": 10,
                "filters": null
            },
            "73": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Ceramic Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 73,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_56.jpg",
                "similar_images": [],
                "cat_b_id": 10,
                "filters": null
            },
            "74": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Wooden Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 74,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_57.jpg",
                "similar_images": [],
                "cat_b_id": 11,
                "filters": null
            },
            "75": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Wooden Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 75,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_58.jpg",
                "similar_images": [],
                "cat_b_id": 11,
                "filters": null
            },
            "76": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Wooden Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 76,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_60.jpg",
                "similar_images": [],
                "cat_b_id": 11,
                "filters": null
            },
            "77": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Wooden Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 77,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_61.jpg",
                "similar_images": [],
                "cat_b_id": 11,
                "filters": null
            },
            "78": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Wooden Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 78,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_62.jpg",
                "similar_images": [],
                "cat_b_id": 11,
                "filters": null
            },
            "79": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Wooden Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 79,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_64.jpg",
                "similar_images": [],
                "cat_b_id": 11,
                "filters": null
            },
            "80": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Random Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 80,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_65.jpg",
                "similar_images": [],
                "cat_b_id": 12,
                "filters": null
            },
            "81": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Random Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 81,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_66.jpg",
                "similar_images": [],
                "cat_b_id": 12,
                "filters": null
            },
            "82": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Random Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 82,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_67.jpg",
                "similar_images": [],
                "cat_b_id": 12,
                "filters": null
            },
            "83": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Random Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 83,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_68.jpg",
                "similar_images": [],
                "cat_b_id": 12,
                "filters": null
            },
            "84": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Random Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 84,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_69.jpg",
                "similar_images": [],
                "cat_b_id": 12,
                "filters": null
            },
            "85": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Random Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 85,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_70.jpg",
                "similar_images": [],
                "cat_b_id": 12,
                "filters": null
            },
            "86": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Tiles",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["1200", "1200"],
                "id": 86,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_71.jpg",
                "similar_images": [],
                "cat_b_id": 8,
                "filters": null
            },
            "87": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Marble",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["1200", "1200"],
                "id": 87,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_72.jpg",
                "similar_images": [],
                "cat_b_id": 13,
                "filters": null
            },
            "88": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Marble",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["1200", "1200"],
                "id": 88,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_73.jpg",
                "similar_images": [],
                "cat_b_id": 13,
                "filters": null
            },
            "89": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Marble",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["1200", "1200"],
                "id": 89,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_75.jpg",
                "similar_images": [],
                "cat_b_id": 13,
                "filters": null
            },
            "90": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Marble",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["1200", "1200"],
                "id": 90,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_76.jpg",
                "similar_images": [],
                "cat_b_id": 13,
                "filters": null
            },
            "91": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Marble",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["1200", "1200"],
                "id": 91,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_77.jpg",
                "similar_images": [],
                "cat_b_id": 13,
                "filters": null
            },
            "92": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Carpet",
                "cat_b_title": "Type-1",
                "grout_id": "4",
                "grout_color": "#894545",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["1200", "1200"],
                "id": 92,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_78.jpg",
                "similar_images": [],
                "cat_b_id": 14,
                "filters": null
            },
            "93": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Carpet",
                "cat_b_title": "Type-1",
                "grout_id": "1",
                "grout_color": "#aeaeae",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["1200", "1200"],
                "id": 93,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_79.jpg",
                "similar_images": [],
                "cat_b_id": 14,
                "filters": null
            },
            "94": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Carpet",
                "cat_b_title": "Type-1",
                "grout_id": "4",
                "grout_color": "#894545",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 94,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_80.jpg",
                "similar_images": [],
                "cat_b_id": 14,
                "filters": null
            },
            "95": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Carpet",
                "cat_b_title": "Type-1",
                "grout_id": "7",
                "grout_color": "#575757",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 95,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_81.jpg",
                "similar_images": [],
                "cat_b_id": 14,
                "filters": null
            },
            "96": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Carpet",
                "cat_b_title": "Type-1",
                "grout_id": "7",
                "grout_color": "#575757",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 96,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_82.jpg",
                "similar_images": [],
                "cat_b_id": 14,
                "filters": null
            },
            "97": {
                "tile_type": 2,
                "name": "Title",
                "cat_a_title": "Carpet",
                "cat_b_title": "Type-1",
                "grout_id": "7",
                "grout_color": "#575757",
                "with_no_grouth": false,
                "price": "-",
                "link": "-",
                "size": ["600", "600"],
                "id": 97,
                "image": "<?php echo str_replace("/","\/", get_template_directory_uri()); ?>\/images\/tile_83.jpg",
                "similar_images": [],
                "cat_b_id": 14,
                "filters": null
            }
        };
*/