<?php
    require('career.php');
    require('customizr.php');
    require('enqueue.php');
    require('theme-support.php');
    require('nav.php');
    require('news.php');
    require('project.php');
    require('metabox.php');